#!/bin/bash

# You may have to adjust the following two paths.
CLANG=/usr/bin/clang
PASS_PLUGIN=/usr/lib/PerfInstrPass.so

FLAGS="-g -fno-discard-value-names -lperfRT -fpass-plugin=$PASS_PLUGIN -fuse-ld=lld"

# -lstdc++: perfRT is written in C++
$CLANG $FLAGS -lstdc++ "$@" -Wno-error=unused-command-line-argument
